import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <div className={`${inter.className} min-h-screen`}>{children}</div>;
}
