import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { redirect } from "next/navigation";
import { getServerSession } from "next-auth";
import { authConfig } from "@/lib/auth";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function ProjectLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authConfig);

  console.log("session:", session);

  if (!session) {
    redirect("/sign-in");
  }

  return <div className={`${inter.className} min-h-screen`}>{children}</div>;
}
