import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../../globals.css";
import SidebarNavigation from "@/components/layout/project/SidebarNavigation";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProjectLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={`${inter.className} min-h-screen bg-gray-50`}>
      <div className="flex justify-center">
        <div className="flex w-[90%] max-w-400">
          <SidebarNavigation />
          <main className="py-8 px-6">{children}</main>
        </div>
      </div>
    </div>
  );
}
